### ISSUE TITLE
Add links to transcripts in /Presentations

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/siliconsalon.info#1]
@Kanzure has added transcripts at his bitcoin transcripts site for the other presentations, they should be linked in.

https://diyhpl.us/wiki/transcripts/silicon-salon/

**Comment by ChristopherA** [comment]
I have added the transcript buttons for those in @Kanzure's website.

We only need to add mine once it is available. Bryan?

**Comment by kanzure** [comment]
> We only need to add mine once it is available. Bryan?

https://diyhpl.us/wiki/transcripts/silicon-salon/intro/

**Comment by ChristopherA** [comment]
Thanks Bryan 🙏🏼

I've added this link in https://github.com/BlockchainCommons/siliconsalon.info/commit/35a7edf13d6c95bafa0e71cc6bc475f7c06df61d  and have tested the website. Closing.
